In [2]:
pip install scikit-learn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 85.6 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [51]:
pip install xgboost

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.9/153.9 MB 144.8 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.0/199.0 MB 120.1 MB/s eta 0:00:0000:0100:01
Note: you may need to restart the kernel to use updated packages.


In [1]:
# Importing the required libraries (install in your environment first)
import numpy as np
import pandas as pd
from math import log2, sqrt
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_svmlight_file

In [48]:
# Read in data from your datafile or the provided datafile in this folder to classify QRNG data. 
# Suggested classification strategies include QRNG vs PRNG, QPU vs Simulator, or by individual QPU

#Sample datafile of QRNG (IBM QPUs) vs PRNG data, 12k lines each. Label 1 is QRNG, label 2 is PRNG
data_filePath = 'QRNGvsPRNG_TrainingData.txt'

# Read data file, make dataframe, process labels, and combine/concatenate individual input lines into
# larger input lines to create training and testing datasets to input into gradient boosting model.
# Hint: use train_test_split method from sklearn



df = pd.read_csv(data_filePath, sep=" ", names=['RNG String', 'Quantum or Classical'])

# Convert 'Quantum or Classical' labels to numeric values (e.g., 1 for QRNG, 2 for PRNG)
# df['Quantum or Classical'] = df['Quantum or Classical'].apply(lambda x: 1 if x == 'QRNG' else 2)

# Split the RNG string into individual bits/characters for processing (assuming the string is made of bits)
df['RNG String'] = df['RNG String'].apply(lambda x: list(map(int, list(x))))


# Prepare input features (X) and target labels (y)
X = pd.DataFrame(df['RNG String'].tolist())
X = np.array(X)
y = np.array(df['Quantum or Classical'])
# print(X)
# print(sorted(y))
# print(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
print(X_train)
print(y_train)

[[0 1 1 ... 0 0 1]
 [1 1 0 ... 1 0 1]
 [1 0 1 ... 1 0 1]
 ...
 [1 1 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [1 0 1 ... 1 0 1]]
[1 2 2 ... 1 2 2]


In [52]:
# A skeleton for running your training dataframe through a SKLearn gradient boosting model. 
# You can also use other ML frameworks such as Pytorch, XGBoost, etc

from sklearn.ensemble import GradientBoostingClassifier
import xgboost as xgb

# Create the Gradient Boosting classifier
xgb_model = xgb.XGBClassifier(random_state=42)

# Train the model. Define X_train and y_train from your training dataframe using 
# sklearns train_test_split method
xgb_model.fit(X_train, y_train, eval_set=[(X_test, y_test)])

y1 = xgb_model.predict(X_train)
accuracy = accuracy_score(y_train, y1)
print("Training accuracy: ", accuracy)

# Make predictions on the test set
y_pred_gb = xgb_model.predict(X_test)

# Calculate the accuracy of the Gradient Boosting model
accuracy_gb = accuracy_score(y_test, y_pred_gb)
print("Gradient Boosting Accuracy: ", accuracy_gb)

ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1], got [1 2]